dataset_key = "dataset_name"
subset_key = "subset"

# SUPPORTED DATASETS
available_datasets = {
    "conll": {dataset_key: "conll2003"},
    "spanish": {dataset_key: "conll2002", subset_key: "es"},
    "dutch": {dataset_key: "conll2002", subset_key: "nl"},
    "finnish": {dataset_key: "finer"},
    "ontonotes": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "arabic": {dataset_key: "conll2012_ontonotesv5", subset_key: "arabic_v4"},
    "chinese": {dataset_key: "conll2012_ontonotesv5", subset_key: "chinese_v4"},
    "fewnerd-inter": {dataset_key: "dfki-nlp/few-nerd", subset_key: "inter"},
    "fewnerd-intra": {dataset_key: "dfki-nlp/few-nerd", subset_key: "intra"},
    "fewnerd-supervised": {dataset_key: "dfki-nlp/few-nerd", subset_key: "supervised"},
    "ontonotes_AB": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_AC": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_BC": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_A": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_B": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_C": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "ontonotes_15": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "arabic_15": {dataset_key: "conll2012_ontonotesv5", subset_key: "arabic_v4"},
    "chinese_15": {dataset_key: "conll2012_ontonotesv5", subset_key: "chinese_v4"},
    "ontonotes_3": {dataset_key: "conll2012_ontonotesv5", subset_key: "english_v12"},
    "arabic_3": {dataset_key: "conll2012_ontonotesv5", subset_key: "arabic_v4"},
    "chinese_3": {dataset_key: "conll2012_ontonotesv5", subset_key: "chinese_v4"},
}

alphabetical_label_name_map = {
    "O": "O",
    "B-PER": "A",
    "I-PER": "A",
    "B-ORG": "B",
    "I-ORG": "B",
    "B-LOC": "C",
    "I-LOC": "C",
    "B-MISC": "D",
    "I-MISC": "D",
    "B-PERSON": "A",
    "I-PERSON": "A",
    "B-FAC": "E",
    "I-FAC": "E",
    "B-CARDINAL": "F",
    "I-CARDINAL": "F",
    "B-EVENT": "G",
    "I-EVENT": "G",
    "B-GPE": "H",
    "I-GPE": "H",
    "B-LANGUAGE": "I",
    "I-LANGUAGE": "I",
    "B-LAW": "J",
    "I-LAW": "J",
    "B-MONEY": "K",
    "I-MONEY": "K",
    "B-NORP": "L",
    "I-NORP": "L",
    "B-ORDINAL": "M",
    "I-ORDINAL": "M",
    "B-PERCENT": "N",
    "I-PERCENT": "N",
    "B-PRODUCT": "O",
    "I-PRODUCT": "O",
    "B-QUANTITY": "P",
    "I-QUANTITY": "P",
    "B-TIME": "Q",
    "I-TIME": "Q",
    "B-WORK_OF_ART": "R",
    "I-WORK_OF_ART": "R",
    "B-PRO": "O",
    "I-PRO": "O",
    "B-DATE": "T",
    "I-DATE": "T",
}

unprocessed_label_name_map = {
    "O": "O",
    "B-PER": "PER",
    "I-PER": "PER",
    "B-ORG": "ORG",
    "I-ORG": "ORG",
    "B-LOC": "LOC",
    "I-LOC": "LOC",
    "B-MISC": "MISC",
    "I-MISC": "MISC",
    "B-PERSON": "PERSON",
    "I-PERSON": "PERSON",
    "B-FAC": "FAC",
    "I-FAC": "FAC",
    "B-CARDINAL": "CARDINAL",
    "I-CARDINAL": "CARDINAL",
    "B-EVENT": "EVENT",
    "I-EVENT": "EVENT",
    "B-GPE": "GPE",
    "I-GPE": "GPE",
    "B-LANGUAGE": "LANGUAGE",
    "I-LANGUAGE": "LANGUAGE",
    "B-LAW": "LAW",
    "I-LAW": "LAW",
    "B-MONEY": "MONEY",
    "I-MONEY": "MONEY",
    "B-NORP": "NORP",
    "I-NORP": "NORP",
    "B-ORDINAL": "ORDINAL",
    "I-ORDINAL": "ORDINAL",
    "B-PERCENT": "PERCENT",
    "I-PERCENT": "PERCENT",
    "B-PRODUCT": "PRODUCT",
    "I-PRODUCT": "PRODUCT",
    "B-QUANTITY": "QUANTITY",
    "I-QUANTITY": "QUANTITY",
    "B-TIME": "TIME",
    "I-TIME": "TIME",
    "B-WORK_OF_ART": "WORK_OF_ART",
    "I-WORK_OF_ART": "WORK_OF_ART",
    "B-PRO": "PRO",
    "I-PRO": "PRO",
    "B-DATE": "DATE",
    "I-DATE": "DATE",
}

# LABEL MAP FOR TART
label_name_map = {
    "O": "O",
    "B-PER": "person",
    "I-PER": "person",
    "B-ORG": "organization",
    "I-ORG": "organization",
    "B-LOC": "location",
    "I-LOC": "location",
    "B-MISC": "miscellaneous",
    "I-MISC": "miscellaneous",
    "B-PERSON": "person",
    "I-PERSON": "person",
    "B-FAC": "building",
    "I-FAC": "building",
    "B-CARDINAL": "cardinal",
    "I-CARDINAL": "cardinal",
    "B-EVENT": "event",
    "I-EVENT": "event",
    "B-GPE": "geopolitical",
    "I-GPE": "geopolitical",
    "B-LANGUAGE": "language",
    "I-LANGUAGE": "language",
    "B-LAW": "law",
    "I-LAW": "law",
    "B-MONEY": "money",
    "I-MONEY": "money",
    "B-NORP": "affiliation",
    "I-NORP": "affiliation",
    "B-ORDINAL": "ordinal",
    "I-ORDINAL": "ordinal",
    "B-PERCENT": "percentage",
    "I-PERCENT": "percentage",
    "B-PRODUCT": "product",
    "I-PRODUCT": "product",
    "B-QUANTITY": "quantity",
    "I-QUANTITY": "quantity",
    "B-TIME": "time",
    "I-TIME": "time",
    "B-WORK_OF_ART": "art",
    "I-WORK_OF_ART": "art",
    "B-PRO": "product",
    "I-PRO": "product",
    "B-DATE": "date",
    "I-DATE": "date",
}

# CROSS LINGUAL MAP
chinese_name_map = {
    "O": "O",
    "B-PER": "人",
    "I-PER": "人",
    "B-ORG": "组织",
    "I-ORG": "组织",
    "B-LOC": "地点",
    "I-LOC": "地点",
    "B-MISC": "各种各样的",
    "I-MISC": "各种各样的",
    "B-PERSON": "人",
    "I-PERSON": "人",
    "B-FAC": "建造",
    "I-FAC": "建造",
    "B-CARDINAL": "红衣主教",
    "I-CARDINAL": "红衣主教",
    "B-EVENT": "事件",
    "I-EVENT": "事件",
    "B-GPE": "地缘政治",
    "I-GPE": "地缘政治",
    "B-LANGUAGE": "语",
    "I-LANGUAGE": "语",
    "B-LAW": "法律",
    "I-LAW": "法律",
    "B-MONEY": "钱",
    "I-MONEY": "钱",
    "B-NORP": "联系",
    "I-NORP": "联系",
    "B-ORDINAL": "序数",
    "I-ORDINAL": "序数",
    "B-PERCENT": "百分比",
    "I-PERCENT": "百分比",
    "B-PRODUCT": "产品",
    "I-PRODUCT": "产品",
    "B-QUANTITY": "数量",
    "I-QUANTITY": "数量",
    "B-TIME": "时间",
    "I-TIME": "时间",
    "B-WORK_OF_ART": "艺术",
    "I-WORK_OF_ART": "艺术",
    "B-PRO": "产品",
    "I-PRO": "产品",
    "B-DATE": "日期",
    "I-DATE": "日期",
}

arabic_name_map = {
    "O": "O",
    "B-PER": "شخص",
    "I-PER": "شخص",
    "B-ORG": "منظمة",
    "I-ORG": "منظمة",
    "B-LOC": "موقعك",
    "I-LOC": "موقعك",
    "B-MISC": "متفرقات",
    "I-MISC": "متفرقات",
    "B-PERSON": "شخص",
    "I-PERSON": "شخص",
    "B-FAC": "بناء",
    "I-FAC": "بناء",
    "B-CARDINAL": "أساسي",
    "I-CARDINAL": "أساسي",
    "B-EVENT": "حدث",
    "I-EVENT": "حدث",
    "B-GPE": "الجيوسياسية",
    "I-GPE": "الجيوسياسية",
    "B-LANGUAGE": "لغة",
    "I-LANGUAGE": "لغة",
    "B-LAW": "قانون",
    "I-LAW": "قانون",
    "B-MONEY": "مال",
    "I-MONEY": "مال",
    "B-NORP": "الانتماء",
    "I-NORP": "الانتماء",
    "B-ORDINAL": "ترتيبي",
    "I-ORDINAL": "ترتيبي",
    "B-PERCENT": "النسبة المئوية",
    "I-PERCENT": "النسبة المئوية",
    "B-PRODUCT": "منتج",
    "I-PRODUCT": "منتج",
    "B-QUANTITY": "كمية",
    "I-QUANTITY": "كمية",
    "B-TIME": "زمن",
    "I-TIME": "زمن",
    "B-WORK_OF_ART": "فن",
    "I-WORK_OF_ART": "فن",
    "B-PRO": "منتج",
    "I-PRO": "منتج",
    "B-DATE": "تاريخ",
    "I-DATE": "تاريخ",
}

finnish_name_map = {
    "O": "O",
    "B-DATE": "Päivämäärä",
    "B-EVENT": "tapahtuma",
    "B-LOC": "sijainti",
    "B-ORG": "organisaatio",
    "B-PER": "henkilö",
    "B-PRO": "tuote",
    "I-DATE": "Päivämäärä",
    "I-EVENT": "tapahtuma",
    "I-LOC": "sijainti",
    "I-ORG": "organisaatio",
    "I-PER": "henkilö",
    "I-PRO": "tuote"
}

# CROSS LINGUAL
cross_lingual_eval_tags = [
    "B-PERSON",
    "I-PERSON",
    "B-ORG",
    "I-ORG",
    "B-LOC",
    "I-LOC",
    "O"
]

# TAG SET EXTENSION GROUPS AS IN YANG (2020)
group_a = [
    "B-ORG",
    "B-NORP",
    "B-ORDINAL",
    "B-WORK_OF_ART",
    "B-QUANTITY",
    "B-LAW",
    "I-ORG",
    "I-NORP",
    "I-ORDINAL",
    "I-WORK_OF_ART",
    "I-QUANTITY",
    "I-LAW",
    "O",
]
group_b = [
    "B-GPE",
    "B-CARDINAL",
    "B-PERCENT",
    "B-TIME",
    "B-EVENT",
    "B-LANGUAGE",
    "I-GPE",
    "I-CARDINAL",
    "I-PERCENT",
    "I-TIME",
    "I-EVENT",
    "I-LANGUAGE",
    "O",
]
group_c = [
    "B-PERSON",
    "B-DATE",
    "B-MONEY",
    "B-LOC",
    "B-FAC",
    "B-PRODUCT",
    "I-PERSON",
    "I-DATE",
    "I-MONEY",
    "I-LOC",
    "I-FAC",
    "I-PRODUCT",
    "O",
]

# GROUPING OF DATASETS FOR PROCESSING
standard_datasets = ["conll", "spanish", "dutch", "finnish"]

fewnerd_datasets = ["fewnerd-inter", "fewnerd-intra", "fewnerd-supervised"]

ontonotes_datasets = ["ontonotes", "arabic", "chinese"]
cross_lingual_ontonotes_datasets = ["ontonotes_15", "arabic_15", "chinese_15", "ontonotes_3", "arabic_3", "chinese_3"]
tagset_extension_datasets = [
    "ontonotes_AB",
    "ontonotes_AC",
    "ontonotes_BC",
    "ontonotes_A",
    "ontonotes_B",
    "ontonotes_C",
] + cross_lingual_ontonotes_datasets
all_ontonotes = ontonotes_datasets + tagset_extension_datasets
