# Hyperparameter configs

config: configs/config.yaml
cuda: True

output_dir: B
experiment: tars_kshot

runs: 5
final_test: True

language_model: pretrained_models/AC0
corpus: ontonotes_B
save_model: False
train_batch_size: 4
eval_batch_size: 32
lr: 5e-5
epochs: 30
num_negatives: none

k: 1
sampling_mode: soft
reuse_decoder_weights: False
reuse_corpus_for_weights: conll


