# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: pretrained_models/ontonotes_AB_IOscheme
experiment: tars_pretain_IOscheme

runs: 1
#set_seed: False
final_test: True

language_model: bert-base-cased
corpus: ontonotes_AB
save_model: True
train_batch_size: 8
eval_batch_size: 8
lr: 5e-5
epochs: 10

k: 2
sampling_mode: strict
reuse_decoder_weights: False
reuse_corpus_for_weights: conll

num_negatives: one