# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: conll_tars_zeroshot
experiment: tars_zeroshot

runs: 1
#set_seed: False
final_test: True

language_model: pretrained_models/tars_conll/run1
corpus: conll
save_model: False
train_batch_size: 8
eval_batch_size: 16
lr: 5e-5
epochs: 10

k: 1
sampling_mode: strict
reuse_decoder_weights: False
reuse_corpus_for_weights: conll

num_negatives: all