# Hyperparameter configs

config: configs/config.yaml
cuda: True

output_dir: pretrained_models/AC2
experiment: tars_pretrain

runs: 4
final_test: True

language_model: bert-base-cased
corpus: ontonotes_AC
save_model: True
train_batch_size: 64
eval_batch_size: 64
lr: 5e-5
epochs: 10
num_negatives: two

k: 1
sampling_mode: soft
reuse_decoder_weights: False
reuse_corpus_for_weights: conll


