# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: test_baseline
experiment: baseline

runs: 1
set_seed: False
final_test: True

language_model: bert-base-cased
corpus: conll
save_model: False
train_batch_size: 8
eval_batch_size: 16
lr: 5e-5
epochs: 10