# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: pretrained_models/AB0
experiment: tars_pretrain

runs:
#set_seed: False
final_test: True

language_model: bert-base-cased
corpus: ontonotes_AB
save_model: True
train_batch_size: 16
eval_batch_size: 16
lr: 5e-5
epochs: 10

k: 1
sampling_mode: soft
reuse_decoder_weights: False
reuse_corpus_for_weights: conll

num_negatives: none
