# Hyperparameter configs

config: configs/config.yaml
cuda: True

output_dir: AS
experiment: eval_crossling_kshot

runs: 5
final_test: True

language_model: bert-base-cased
corpus: finnish
save_model: False
train_batch_size: 4
eval_batch_size: 64
lr: 5e-6
epochs: 10
num_negatives: all

k: 32
sampling_mode: soft
reuse_decoder_weights: True
reuse_corpus_for_weights: conll


