# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: test_kshot_sampling
experiment: tars_kshot

runs: 1
#set_seed: False
final_test: True

language_model: bert-base-cased
corpus: ontonotes_A
save_model: False
train_batch_size: 8
eval_batch_size: 8
lr: 5e-5
epochs: 10

k: 5
sampling_mode: soft
reuse_decoder_weights: False
reuse_corpus_for_weights: conll

num_negatives: all