# Hyperparameter configs

config: configs/config.yaml
cuda: True
cuda_devices: "1"

output_dir: test_tars
experiment: tars_pretrain

runs: 1
set_seed: False
final_test: True

language_model: bert-base-cased
corpus: conll
save_model: False
train_batch_size: 8
eval_batch_size: 16
lr: 5e-5
epochs: 10

k: 32
reuse_decoder_weights: True
reuse_corpus_for_weights: conll